apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homeservarr-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/majorrabbid/HomeServarr
  ref:
    branch: main
