apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeservarr-jarvis-agent
  namespace: homeservarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeservarr-jarvis-agent
  template:
    metadata:
      labels:
        app: homeservarr-jarvis-agent
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: jarvis-agent
          image: ghcr.io/majorrabbid/homeservarr-jarvis-agent:latest
          imagePullPolicy: Always
          command:
            - /usr/local/bin/homeservarr-agent

          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
